var annotated_dup =
[
    [ "chain", "namespacechain.html", "namespacechain" ],
    [ "ARchain", "class_a_rchain.html", "class_a_rchain" ],
    [ "ARchain< Newtonian< typename EvolvedData::Scalar >, EvolvedData, Regularitor >", "class_a_rchain_3_01_newtonian_3_01typename_01_evolved_data_1_1_scalar_01_4_00_01_evolved_data_00_01_regularitor_01_4.html", "class_a_rchain_3_01_newtonian_3_01typename_01_evolved_data_1_1_scalar_01_4_00_01_evolved_data_00_01_regularitor_01_4" ],
    [ "BSIterator", "class_b_s_iterator.html", "class_b_s_iterator" ],
    [ "constIterator", "classconst_iterator.html", "classconst_iterator" ],
    [ "dynamics", "classdynamics.html", "classdynamics" ],
    [ "dynamicSystem", "classdynamic_system.html", "classdynamic_system" ],
    [ "errhand", "classerrhand.html", "classerrhand" ],
    [ "GAR", "class_g_a_r.html", "class_g_a_r" ],
    [ "logH", "classlog_h.html", "classlog_h" ],
    [ "Newtonian", "class_newtonian.html", "class_newtonian" ],
    [ "NoRegu", "class_no_regu.html", "class_no_regu" ],
    [ "particleSystem", "classparticle_system.html", "classparticle_system" ],
    [ "PN1th", "class_p_n1th.html", "class_p_n1th" ],
    [ "reguDynamics", "classregu_dynamics.html", "classregu_dynamics" ],
    [ "reguSystem", "classregu_system.html", "classregu_system" ],
    [ "reguSystem< Newtonian< typename EvolvedData::Scalar >, EvolvedData, Regularitor >", "classregu_system_3_01_newtonian_3_01typename_01_evolved_data_1_1_scalar_01_4_00_01_evolved_data_00_01_regularitor_01_4.html", "classregu_system_3_01_newtonian_3_01typename_01_evolved_data_1_1_scalar_01_4_00_01_evolved_data_00_01_regularitor_01_4" ],
    [ "symplectic10th", "classsymplectic10th.html", "classsymplectic10th" ],
    [ "symplectic2th", "classsymplectic2th.html", "classsymplectic2th" ],
    [ "symplectic4th", "classsymplectic4th.html", "classsymplectic4th" ],
    [ "symplectic6th", "classsymplectic6th.html", "classsymplectic6th" ],
    [ "symplectic8th", "classsymplectic8th.html", "classsymplectic8th" ],
    [ "TTL", "class_t_t_l.html", "class_t_t_l" ],
    [ "vec3", "structvec3.html", "structvec3" ]
];